import useAuthStore from '@/stores/authStore'

/**
 * Branded header that ONLY appears on printed output (or "Save as PDF").
 * On screen, this component renders nothing.
 *
 * Layout (paper):
 *   ─────────────────────────────────────────────────
 *   Storey · ConTech ERP                    Generated:
 *   storeyinfra.com                         15 May 2026, 14:23
 *   ─────────────────────────────────────────────────
 *   <Report title>
 *   <Optional subtitle — e.g. site name, period>
 *   Tenant: <company name>     Generated by: <user name>
 */
export default function PrintHeader({ title, subtitle }) {
  const profile = useAuthStore((s) => s.profile)
  const generated = new Date().toLocaleString('en-IN', {
    day: '2-digit', month: 'short', year: 'numeric',
    hour: '2-digit', minute: '2-digit', hour12: false,
  })

  return (
    <header className="print-only mb-4">
      <div className="flex items-start justify-between border-b-2 border-gray-900 pb-2 mb-3">
        <div>
          <h1 className="font-display text-xl font-bold">Storey</h1>
          <p className="text-[10pt] text-gray-700">
            ConTech ERP · storeyinfra.com
          </p>
        </div>
        <div className="text-right text-[10pt] text-gray-700">
          <p className="font-medium">Generated</p>
          <p>{generated}</p>
        </div>
      </div>

      <h2 className="font-display text-lg font-semibold leading-tight">{title}</h2>
      {subtitle && <p className="text-sm text-gray-700">{subtitle}</p>}

      <p className="mt-2 text-[10pt] text-gray-600">
        {profile?.tenant?.name && (
          <>
            <span className="font-medium">Tenant:</span> {profile.tenant.name}
            <span className="mx-2">·</span>
          </>
        )}
        {profile?.full_name && (
          <>
            <span className="font-medium">Generated by:</span> {profile.full_name}
          </>
        )}
      </p>
    </header>
  )
}
