import { useEffect, useState, useMemo } from 'react'
import { Hammer, Download, CalendarDays } from 'lucide-react'
import useAuthStore from '@/stores/authStore'
import useReportsStore from '@/stores/reportsStore'
import { WORK_TYPES, WORK_TYPE_COLORS } from '@/lib/materialPresets'
import { downloadWorkbook, fmtINR, downloadSheet } from '@/lib/exportXLS'
import { formatINR } from '@/lib/utils'
import PrintButton from '@/components/print/PrintButton'
import PrintHeader from '@/components/print/PrintHeader'
import StatCard from '@/components/ui/StatCard'
import ShareReportButton from '@/components/ui/ShareReportButton'
import { cn } from '@/lib/utils'

const WORK_LABEL = Object.fromEntries(WORK_TYPES.map(({ value, label }) => [value, label]))

function toLocalISO(d) {
  return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}-${String(d.getDate()).padStart(2, '0')}`
}
function todayISO() { return toLocalISO(new Date()) }
function firstOfMonthISO() {
  const d = new Date(); d.setDate(1); return toLocalISO(d)
}
function shortDate(iso) {
  return new Date(iso + 'T00:00:00').toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })
}

export default function ConsumptionReportTab({ sites }) {
  const profile  = useAuthStore((s) => s.profile)
  const tenantId = profile?.tenant_id
  const { consumptionData, consumptionLoading, fetchConsumptionReport } = useReportsStore()

  const [siteId,    setSiteId]    = useState('')
  const [startDate, setStartDate] = useState(firstOfMonthISO)
  const [endDate,   setEndDate]   = useState(todayISO)
  const [workType,  setWorkType]  = useState('')
  const [category,  setCategory]  = useState('') // '' | 'consumable' | 'equipment'
  const [view,      setView]      = useState('summary') // 'summary' | 'detail'

  useEffect(() => {
    if (tenantId && startDate && endDate) {
      fetchConsumptionReport(tenantId, siteId || null, startDate, endDate)
    }
  }, [tenantId, siteId, startDate, endDate])

  const filteredRows = useMemo(() => {
    if (!consumptionData) return []
    return consumptionData.rows.filter((r) => {
      if (workType && r.materials?.work_type !== workType) return false
      if (category && r.materials?.category !== category) return false
      return true
    })
  }, [consumptionData, workType, category])

  const filteredSummary = useMemo(() => {
    if (!consumptionData) return []
    return consumptionData.summary.filter((s) => {
      if (workType && s.work_type !== workType) return false
      if (category && s.category !== category) return false
      return true
    })
  }, [consumptionData, workType, category])

  const totalValue = filteredSummary.reduce((s, r) => s + r.value, 0)
  // Compact format for the stat card (avoids overflow at text-2xl on 360px phones)
  const totalValueCompact = totalValue >= 10000000
    ? `₹${(totalValue / 10000000).toFixed(1)}Cr`
    : totalValue >= 100000
      ? `₹${(totalValue / 100000).toFixed(1)}L`
      : totalValue >= 1000
        ? `₹${Math.round(totalValue / 1000)}k`
        : `₹${totalValue}`

  const siteName    = siteId ? (sites.find((s) => s.id === siteId)?.name ?? '—') : 'All sites'
  const periodLabel = `${shortDate(startDate)} – ${shortDate(endDate)}`

  // Share text — plain-text summary for WhatsApp / email
  const shareText = [
    `📦 *Storey — Material Consumption*`,
    `Site: ${siteName}`,
    `Period: ${periodLabel}`,
    ``,
    `Materials used: ${filteredSummary.length}`,
    `Allocation entries: ${filteredRows.length}`,
    `Total value: ${totalValueCompact}`,
    ``,
    `Generated by Storey · storeyinfra.com`,
  ].join('\n')

  const shareEmailBody = [
    `Material Consumption Report`,
    `Site: ${siteName}`,
    `Period: ${periodLabel}`,
    ``,
    `Materials used: ${filteredSummary.length}`,
    `Allocation entries: ${filteredRows.length}`,
    `Total value: ${totalValueCompact}`,
    ``,
    filteredSummary.map((s) =>
      `• ${s.name} — ${Number(s.total).toLocaleString('en-IN')} ${s.unit}${s.unit_cost > 0 ? ` · ₹${s.value.toLocaleString('en-IN')}` : ''}`
    ).join('\n'),
    ``,
    `Generated by Storey · storeyinfra.com`,
  ].join('\n')

  function handleExport() {
    if (!consumptionData) return
    const sheets = [
      {
        name: 'Summary by material',
        rows: [
          ['Material', 'Brand', 'Category', 'Work type', 'Unit', 'Rate (₹)', 'Qty consumed', 'Value (₹)', 'Entries'],
          ...filteredSummary.map((s) => [
            s.name, s.brand || 'Generic',
            s.category === 'equipment' ? 'Equipment' : 'Consumable',
            WORK_LABEL[s.work_type] ?? s.work_type ?? '—',
            s.unit, s.unit_cost || '', s.total, s.value || '', s.entries,
          ]),
          ['', '', '', '', '', 'Total', '', filteredSummary.reduce((t, s) => t + s.value, 0), ''],
        ],
      },
      {
        name: 'Detail',
        rows: [
          ['Date', 'Material', 'Brand', 'Category', 'Work description', 'Site', 'Rate (₹)', 'Qty consumed', 'Value (₹)', 'Note'],
          ...filteredRows.map((r) => {
            const qty  = Number(r.quantity_allocated)
            const rate = Number(r.materials?.unit_cost ?? 0)
            return [
              r.allocated_date, r.materials?.name ?? '—', r.materials?.brand || 'Generic',
              r.materials?.category === 'equipment' ? 'Equipment' : 'Consumable',
              r.work_description || '—', r.sites?.name ?? '—',
              rate || '', qty, rate > 0 ? qty * rate : '', r.note || '',
            ]
          }),
        ],
      },
    ]
    downloadWorkbook(sheets, `consumption-${startDate}-to-${endDate}`)
  }

  return (
    <div className="space-y-6">
      <PrintHeader
        title="Material Consumption"
        subtitle={`Site: ${siteName} · ${periodLabel}`}
      />

      {/* Filters */}
      <div className="no-print flex flex-wrap items-end gap-3">
        <div>
          <label className="label">From</label>
          <input type="date" className="input py-1.5 text-sm"
            value={startDate} max={endDate}
            onChange={(e) => setStartDate(e.target.value)} />
        </div>
        <div>
          <label className="label">To</label>
          <input type="date" className="input py-1.5 text-sm"
            value={endDate} min={startDate} max={todayISO()}
            onChange={(e) => setEndDate(e.target.value)} />
        </div>
        <div>
          <label className="label">Site</label>
          <select className="input py-1.5 pr-8 text-sm" value={siteId} onChange={(e) => setSiteId(e.target.value)}>
            <option value="">All sites</option>
            {sites.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}
          </select>
        </div>
        <div>
          <label className="label">Work type</label>
          <select className="input py-1.5 pr-8 text-sm" value={workType} onChange={(e) => setWorkType(e.target.value)}>
            <option value="">All types</option>
            {WORK_TYPES.map(({ value, label }) => <option key={value} value={value}>{label}</option>)}
          </select>
        </div>
        <div>
          <label className="label">Category</label>
          <select className="input py-1.5 pr-8 text-sm" value={category} onChange={(e) => setCategory(e.target.value)}>
            <option value="">All</option>
            <option value="consumable">Consumable</option>
            <option value="equipment">Equipment</option>
          </select>
        </div>
        <div className="ml-auto flex items-center gap-2">
          <PrintButton label="Print" />
          <button
            onClick={handleExport}
            disabled={!filteredRows.length}
            className="btn-secondary flex items-center gap-1.5 text-sm"
          >
            <Download className="h-4 w-4" /> Export XLS
          </button>
          {consumptionData && filteredRows.length > 0 && (
            <ShareReportButton
              text={shareText}
              emailSubject={`Storey Consumption Report — ${siteName} · ${periodLabel}`}
              emailBody={shareEmailBody}
            />
          )}
        </div>
      </div>

      {/* Summary cards */}
      {consumptionData && (
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-3">
          <StatCard label="Materials used"    value={filteredSummary.length}        icon={Hammer}      color="brand" />
          <StatCard label="Allocation entries" value={filteredRows.length}          icon={Hammer}      color="sage"  />
          <StatCard label="Total value"       value={totalValueCompact}             icon={Hammer}      color="red"   />
          <StatCard label="Period"            value={periodLabel}                   icon={CalendarDays} color="brand"
            valueClass="text-sm font-semibold leading-snug" />
        </div>
      )}

      {/* View toggle */}
      <div className="no-print flex gap-1 border-b border-gray-200">
        {[{ id: 'summary', label: 'By material' }, { id: 'detail', label: 'All entries' }].map((t) => (
          <button
            key={t.id}
            onClick={() => setView(t.id)}
            className={cn(
              'px-4 py-2 text-sm font-medium border-b-2 -mb-px transition-colors',
              view === t.id ? 'border-brand-600 text-brand-700' : 'border-transparent text-gray-500 hover:text-gray-700',
            )}
          >
            {t.label}
          </button>
        ))}
      </div>

      {consumptionLoading ? (
        <p className="card px-5 py-8 text-sm text-gray-500">Loading…</p>
      ) : !filteredRows.length ? (
        <p className="card px-5 py-8 text-sm text-gray-500 text-center">
          No consumption recorded for this period.
        </p>
      ) : view === 'summary' ? (
        /* ── Summary: one row per material ─────────────────────────── */
        <div className="card overflow-hidden">
          <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-100">
            <thead className="bg-gray-50">
              <tr>
                {['Material', 'Brand', 'Category', 'Work type', 'Unit', 'Qty consumed', 'Value (₹)', 'Entries'].map((h) => (
                  <th key={h} className="px-4 py-2.5 text-left text-xs font-medium text-gray-500 uppercase tracking-wide">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 bg-white">
              {filteredSummary.map((s, i) => (
                <tr key={i} className="hover:bg-gray-50">
                  <td className="px-4 py-2.5 text-sm font-medium text-gray-900">{s.name}</td>
                  <td className="px-4 py-2.5 text-sm text-gray-500">{s.brand || <span className="text-gray-300">Generic</span>}</td>
                  <td className="px-4 py-2.5">
                    <span className={cn('text-xs px-2 py-0.5 rounded-full font-medium', s.category === 'equipment' ? 'bg-blue-100 text-blue-700' : 'bg-gray-100 text-gray-600')}>
                      {s.category === 'equipment' ? 'Equipment' : 'Consumable'}
                    </span>
                  </td>
                  <td className="px-4 py-2.5">
                    {s.work_type ? (
                      <span className={`text-xs px-2 py-0.5 rounded-full font-medium ${WORK_TYPE_COLORS[s.work_type]}`}>
                        {WORK_LABEL[s.work_type] ?? s.work_type}
                      </span>
                    ) : <span className="text-gray-300 text-xs">—</span>}
                  </td>
                  <td className="px-4 py-2.5 text-sm text-gray-600">{s.unit}</td>
                  <td className="px-4 py-2.5 text-sm font-semibold text-gray-900">
                    {Number(s.total).toLocaleString('en-IN')}
                  </td>
                  <td className="px-4 py-2.5 text-sm text-gray-900">
                    {s.unit_cost > 0 ? formatINR(s.value) : <span className="text-gray-300">—</span>}
                  </td>
                  <td className="px-4 py-2.5 text-sm text-gray-500">{s.entries}</td>
                </tr>
              ))}
              <tr className="bg-gray-50 font-semibold">
                <td colSpan={6} className="px-4 py-2.5 text-right text-sm text-gray-700">Total value</td>
                <td className="px-4 py-2.5 text-sm text-gray-900">{formatINR(totalValue)}</td>
                <td />
              </tr>
            </tbody>
          </table>
          </div>
        </div>
      ) : (
        /* ── Detail: every allocation entry ────────────────────────── */
        <div className="card overflow-hidden">
          <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-100">
            <thead className="bg-gray-50">
              <tr>
                {['Date', 'Material', 'Category', 'Work description', 'Site', 'Qty', 'Value (₹)'].map((h) => (
                  <th key={h} className="px-4 py-2.5 text-left text-xs font-medium text-gray-500 uppercase tracking-wide">{h}</th>
                ))}
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100 bg-white">
              {filteredRows.map((r) => (
                <tr key={r.id} className="hover:bg-gray-50">
                  <td className="px-4 py-2.5 text-sm text-gray-600 whitespace-nowrap">
                    {new Date(r.allocated_date + 'T00:00:00').toLocaleDateString('en-IN', { day: '2-digit', month: 'short' })}
                  </td>
                  <td className="px-4 py-2.5">
                    <p className="text-sm font-medium text-gray-900">{r.materials?.name ?? '—'}</p>
                    {r.materials?.brand && <p className="text-xs text-gray-400">{r.materials.brand}</p>}
                  </td>
                  <td className="px-4 py-2.5">
                    <span className={cn('text-xs px-2 py-0.5 rounded-full font-medium', r.materials?.category === 'equipment' ? 'bg-blue-100 text-blue-700' : 'bg-gray-100 text-gray-600')}>
                      {r.materials?.category === 'equipment' ? 'Equipment' : 'Consumable'}
                    </span>
                  </td>
                  <td className="px-4 py-2.5 text-sm text-gray-700 max-w-xs">
                    {r.work_description || <span className="text-gray-300">—</span>}
                    {r.note && <p className="text-xs text-gray-400 mt-0.5">{r.note}</p>}
                  </td>
                  <td className="px-4 py-2.5 text-sm text-gray-600">{r.sites?.name ?? '—'}</td>
                  <td className="px-4 py-2.5 text-sm font-semibold text-gray-900 whitespace-nowrap">
                    {Number(r.quantity_allocated).toLocaleString('en-IN')} {r.materials?.unit}
                  </td>
                  <td className="px-4 py-2.5 text-sm text-gray-900 whitespace-nowrap">
                    {r.materials?.unit_cost > 0
                      ? formatINR(Number(r.quantity_allocated) * Number(r.materials.unit_cost))
                      : <span className="text-gray-300">—</span>}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
          </div>
        </div>
      )}
    </div>
  )
}
